package com.app.chasel.model;

public enum NotificationType {
    PRICE_DROP,
    ORDER_PLACED,
    SALE_PLACED,
    ORDER_PROCESSING,
    ORDER_CANCELLED,
    SALE_CANCELLED,
    SALE_RETURN_REQUESTED,
    ORDER_RETURN_DISCUSSION,
    ORDER_RETURN_APPROVED,
    SALE_READY,
    SALE_SHIPPED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    SALE_DELIVERED
}
